<a href="https://colab.research.google.com/github/ArtemOsokin/mgpu_python_for_data_analysis/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
np.version.version

'1.23.5'

2) Создать нулевой вектор размера 10

In [66]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3) Создать вектор заполненный 7-ами размера 7

In [70]:
np.array([7]*7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [12]:
np.arange(10, 102, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [13]:
rng = np.random.default_rng(10)
arr = rng.integers(low=0, high=10, size=10)
print(arr)
np.flip(arr)

[7 9 2 2 7 8 5 1 8 5]


array([5, 8, 1, 5, 8, 7, 2, 2, 9, 7])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [32]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [85]:
mat = np.ones(3, dtype=int)
np.diag(mat, k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [94]:
d = np.array([7]*4, dtype=int)
mat = np.matrix([np.arange(1, 5) for _ in range(4)])
np.fill_diagonal(mat, d)
mat

matrix([[7, 2, 3, 4],
        [1, 7, 3, 4],
        [1, 2, 7, 4],
        [1, 2, 3, 7]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [95]:
np.array([np.arange(5) for _ in range(5)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [65]:
rng = np.random.default_rng(10)
arr = np.array(
    [rng.integers(low=0, high=10, size=10) for _ in range(10)],
    dtype=int
)
print(arr)
for row in arr:
  avg = sum(row)/len(row)
  for i in range(len(row)):
    row[i] = row[i] - avg
print(arr)

[[7 9 2 2 7 8 5 1 8 5]
 [1 1 4 6 4 8 0 4 5 9]
 [2 8 0 3 7 5 9 7 9 8]
 [1 9 8 1 9 7 3 1 3 9]
 [7 2 4 8 6 3 1 9 2 5]
 [6 3 5 2 8 6 1 3 6 6]
 [3 1 1 2 7 8 3 6 4 2]
 [5 1 4 1 2 2 0 3 7 6]
 [7 8 0 7 1 3 0 1 4 4]
 [3 4 4 5 6 3 7 6 4 1]]
[[ 1  3 -3 -3  1  2  0 -4  2  0]
 [-3 -3  0  1  0  3 -4  0  0  4]
 [-3  2 -5 -2  1  0  3  1  3  2]
 [-4  3  2 -4  3  1 -2 -4 -2  3]
 [ 2 -2  0  3  1 -1 -3  4 -2  0]
 [ 1 -1  0 -2  3  1 -3 -1  1  1]
 [ 0 -2 -2 -1  3  4  0  2  0 -1]
 [ 1 -2  0 -2 -1 -1 -3  0  3  2]
 [ 3  4 -3  3 -2  0 -3 -2  0  0]
 [-1  0  0  0  1 -1  2  1  0 -3]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [64]:
rng = np.random.default_rng(10)
arr = np.array(
    [rng.integers(low=0, high=10, size=10) for _ in range(10)],
    dtype=int
)
print(arr)
for i in range(10):
  for j in range(10):
    arr[j][i] -= np.median(arr[i])
print(arr)

[[7 9 2 2 7 8 5 1 8 5]
 [1 1 4 6 4 8 0 4 5 9]
 [2 8 0 3 7 5 9 7 9 8]
 [1 9 8 1 9 7 3 1 3 9]
 [7 2 4 8 6 3 1 9 2 5]
 [6 3 5 2 8 6 1 3 6 6]
 [3 1 1 2 7 8 3 6 4 2]
 [5 1 4 1 2 2 0 3 7 6]
 [7 8 0 7 1 3 0 1 4 4]
 [3 4 4 5 6 3 7 6 4 1]]
[[ 1  5 -4 -1  4  6  2  1  6  3]
 [-4 -3 -2  3  1  6 -2  4  3  7]
 [-3  4 -6  0  4  3  6  7  7  6]
 [-4  5  2 -2  6  5  0  1  1  7]
 [ 2 -2 -2  5  3  1 -1  9  0  3]
 [ 1 -1 -1 -1  5  4 -1  3  4  4]
 [-2 -3 -5 -1  4  6  0  6  2  0]
 [ 0 -3 -2 -2  0  0 -1  3  5  4]
 [ 2  4 -6  4 -1  1 -1  1  2  2]
 [-2  0 -2  2  3  1  6  6  2  0]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [30]:
import random
mat = [[random.randint(1, 10) for _ in range(5)] for _ in range(5)]
print(np.array(mat))
for row in mat:
  row.append(max(row))
  row.append(min(row))
np.array(mat)

[[ 8 10  8  1 10]
 [ 6  1  1  1  2]
 [ 1  4  6  2  6]
 [ 4  2  4  6  1]
 [10  6  9  2  1]]


array([[ 8, 10,  8,  1, 10, 10,  1],
       [ 6,  1,  1,  1,  2,  6,  1],
       [ 1,  4,  6,  2,  6,  6,  1],
       [ 4,  2,  4,  6,  1,  6,  1],
       [10,  6,  9,  2,  1, 10,  1]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [76]:
import math


def get_even_odd_matrix(vec: np.ndarray) -> (np.matrix, np.matrix):
  odd, even = [], []
  for i in vec:
    if i%2 == 0:
      odd.append(i)
    else:
      even.append(i)
  odd, even = np.array(odd), np.array(even)
  size = int(math.sqrt(len(odd)))
  return np.matrix(odd.reshape(size, size)), np.matrix(even.reshape(size, size))

vec = np.arange(1, 51)
odd, even = get_even_odd_matrix(vec)
print(odd, even)

mult_mat = np.matrix(np.multiply(odd, even))
print(mult_mat)

np.linalg.det(mult_mat)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]] [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]


0.0

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [73]:
import numpy as np
mat = np.zeros((8,8), dtype=int)
mat[1::2,::2] = 1
mat[::2,1::2] = 1
mat

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])