<a href="https://colab.research.google.com/github/ArtemOsokin/mgpu_python_for_data_analysis/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
np.version.version

'1.23.5'

2) Создать нулевой вектор размера 10

In [66]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3) Создать вектор заполненный 7-ами размера 7

In [70]:
np.array([7]*7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [12]:
np.arange(10, 102, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
arr = np.empty(10)
print(arr)
np.flip(arr)

[4.65651346e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 1.02768292e+248 4.42322913e-062 3.27044298e+179 5.89354880e-091
 1.34001582e-075 1.96567563e-062]


array([1.96567563e-062, 1.34001582e-075, 5.89354880e-091, 3.27044298e+179,
       4.42322913e-062, 1.02768292e+248, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 4.65651346e-310])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [10]:
mat = np.arange(9).reshape(3,3)
np.matrix(mat)

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [85]:
mat = np.ones(3, dtype=int)
np.diag(mat, k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
d = np.arange(1, 5, dtype=int)
mat = np.full((4, 4), 7)
np.fill_diagonal(mat, d)
mat

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [48]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [47]:
matrix = np.random.rand(10, 10)
row_means = np.mean(matrix, axis=1, keepdims=True)
mat = matrix - row_means

print(mat)

[[ 0.16688207  0.04483182  0.17135564  0.07226101  0.08366918 -0.2467071
  -0.15737968  0.29116727 -0.17300406 -0.25307614]
 [-0.34953798  0.27581953 -0.3560051   0.29817939 -0.1516173   0.1505483
  -0.24551083  0.33234442 -0.41484703  0.46062661]
 [ 0.57048584 -0.33079024  0.21581274  0.2334864  -0.31200834 -0.0611806
  -0.02380516 -0.1548675  -0.12125054 -0.0158826 ]
 [-0.10180336  0.20494406 -0.28525279 -0.0648656   0.33754087 -0.13901876
   0.47006971 -0.0444411  -0.24040205 -0.13677098]
 [ 0.0085925   0.01452367 -0.42967744  0.32796962  0.01157082  0.19189612
   0.32885719 -0.22748348 -0.28737891  0.06112991]
 [-0.1237051  -0.17985292  0.38313605 -0.37643949 -0.15196328  0.32425546
  -0.05630158  0.08574135  0.19265139 -0.09752188]
 [-0.16533103  0.14909689  0.16152136  0.18243009 -0.11116597 -0.06266486
  -0.06619281 -0.22023754 -0.15738205  0.28992592]
 [ 0.00928959  0.21407847 -0.10898563 -0.07619287 -0.25134952  0.43221987
  -0.45008219 -0.1785874   0.23281999  0.17678969]
 [-

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [45]:
matrix = np.random.rand(10, 10)
medians = np.median(matrix, axis=0)
mat = matrix - medians
print(mat)

[[ 0.25809186 -0.08466447  0.03461365 -0.18588423 -0.43238337 -0.24513118
  -0.02520666  0.32171758 -0.2524366  -0.38626017]
 [-0.0905157  -0.00181456 -0.12342136  0.05753946  0.0795995   0.38754714
   0.6612023   0.47273755  0.38410518 -0.00985214]
 [-0.18869769 -0.41589162 -0.00433754  0.35038075  0.28927723 -0.03980139
   0.02520666 -0.23762406  0.2006728  -0.27732871]
 [ 0.0905157   0.37578505  0.00433754 -0.03572523 -0.37842352 -0.24840694
   0.58522583 -0.28296348  0.12616076 -0.31668487]
 [-0.51381375 -0.07988873  0.08845804  0.03572523 -0.0359091  -0.05753949
   0.30753732  0.03264679 -0.26863137 -0.11587904]
 [ 0.26040312  0.32611009 -0.35444081 -0.27490366  0.37327483  0.3754492
  -0.25159726  0.4518178  -0.38899321  0.38143665]
 [ 0.0974686  -0.36910602 -0.48501118 -0.29550912  0.0359091   0.34288884
  -0.20225306 -0.12845274  0.29028974  0.50619438]
 [-0.56141579  0.35007187  0.23690965  0.21324859 -0.06812153  0.10930063
  -0.06917052  0.51653393 -0.12616076  0.00985214]
 

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [30]:
import random
mat = [[random.randint(1, 10) for _ in range(5)] for _ in range(5)]
print(np.array(mat))
for row in mat:
  row.append(max(row))
  row.append(min(row))
np.array(mat)

[[ 8 10  8  1 10]
 [ 6  1  1  1  2]
 [ 1  4  6  2  6]
 [ 4  2  4  6  1]
 [10  6  9  2  1]]


array([[ 8, 10,  8,  1, 10, 10,  1],
       [ 6,  1,  1,  1,  2,  6,  1],
       [ 1,  4,  6,  2,  6,  6,  1],
       [ 4,  2,  4,  6,  1,  6,  1],
       [10,  6,  9,  2,  1, 10,  1]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [58]:
import math


def get_even_odd_matrix(vec: np.ndarray) -> tuple[np.matrix, np.matrix]:
  odd, even = vec[vec % 2 == 0], vec[vec % 2 != 0]
  size = int(math.sqrt(len(odd)))
  return np.matrix(odd.reshape(size, size)), np.matrix(even.reshape(size, size))

vec = np.arange(1, 51)
odd, even = get_even_odd_matrix(vec)
print(odd, even)

mult_mat = np.matrix(odd.dot(even))
print(mult_mat)

np.linalg.det(mult_mat)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]] [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]


0.0

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [11]:
import numpy as np
mat = np.zeros((8,8), dtype=int)
mat[1::2,::2] = 1
mat[::2,1::2] = 1
np.matrix(mat)

matrix([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])